const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const GUMROAD_DIR = path.join(__dirname, 'gumroad_products');

// ==================== PRODUCT CATALOG ====================
const PRODUCTS = [
  // --- HABITATS (generated by habitat_generator.js) ---
  {
    id: 'cyberpunk-habitat',
    name: 'Cyberpunk City — Interactive 3D World',
    tagline: 'A living neon metropolis in your browser. No install. No backend.',
    description: `Step into a fully interactive 3D cyberpunk city with nine themed districts, each with unique neon-lit buildings, glowing monuments, and ambient particle effects. Built with Babylon.js — runs in any modern browser.`,
    price: 27,
    category: '3D Environments',
    file: 'cyberpunk',
    type: 'habitat',
    features: [
      '9 unique neon districts (Neon District, The Core, Glitch Zone, etc.)',
      '54 procedurally placed buildings with glowing windows',
      'Animated city center monuments with floating orbs',
      'Ambient particle system (digital rain/energy motes)',
      'Full orbit camera (WASD + mouse)',
      'Bloom post-processing for that cyberpunk glow',
      'Single HTML file — zero dependencies'
    ]
  },
  {
    id: 'fantasy-forest-habitat',
    name: 'Fantasy Forest Realm — Interactive 3D World',
    tagline: 'An enchanted woodland realm of magic and mystery.',
    description: `Explore a mystical forest city with nine themed districts, glowing mushroom dwellings, ancient tree architecture, and ethereal particle effects. A complete interactive 3D world in your browser.`,
    price: 27,
    category: '3D Environments',
    file: 'fantasy_forest',
    type: 'habitat',
    features: [
      '9 unique forest districts (Elven City, Nature Temple, Deep Woods, etc.)',
      '54 themed buildings (Council Tree, Mushroom Den, Dragon Tavern)',
      'Enchanted particle system (glowing fireflies)',
      'Warm green/gold color palette',
      'Animated floating monument orbs',
      'Single HTML file — works immediately'
    ]
  },
  {
    id: 'space-station-habitat',
    name: 'Orbital Space Station — Interactive 3D World',
    tagline: 'Command the stars from your own orbital habitat.',
    description: `A fully interactive 3D space station with nine themed decks — from Command Center to Cargo Bay. Cold blue lighting, zero-g particles, and panoramic star vistas.`,
    price: 27,
    category: '3D Environments',
    file: 'space_station',
    type: 'habitat',
    features: [
      '9 themed station decks (Command Deck, Data Core, Star Temple, etc.)',
      '54 sci-fi structures with metallic finishes',
      'Zero-gravity particle effects',
      'Blue/cool color palette with starfield backdrop',
      'Interactive orbital monument system',
      'Single HTML file — no install needed'
    ]
  },
  {
    id: 'underwater-habitat',
    name: 'Atlantis Underwater City — Interactive 3D World',
    tagline: 'Discover a lost civilization beneath the waves.',
    description: `Dive into a stunning underwater metropolis with coral architecture, bioluminescent lighting, and deep blue atmospheric haze. Nine themed aquatic districts await.`,
    price: 27,
    category: '3D Environments',
    file: 'underwater',
    type: 'habitat',
    features: [
      '9 aquatic districts (Coral Centre, Abyss Archive, Kelp Forest, etc.)',
      '54 themed underwater structures',
      'Bioluminescent particle effects',
      'Deep blue ocean fog and lighting',
      'Bubble particle system',
      'Single HTML file — open and explore'
    ]
  },
  {
    id: 'desert-oasis-habitat',
    name: 'Desert Oasis Kingdom — Interactive 3D World',
    tagline: 'A golden empire rises from the sands.',
    description: `Explore a vast desert kingdom with terracotta architecture, palm-lined oases, and warm amber lighting. Nine themed districts spanning from the Golden City to the Dune Wastes.`,
    price: 27,
    category: '3D Environments',
    file: 'desert_oasis',
    type: 'habitat',
    features: [
      '9 desert districts (Golden City, Sun Temple, Dune Wastes, etc.)',
      '54 sand-colored buildings with warm lighting',
      'Golden amber particle effects',
      'Warm sunset color palette',
      'Palm tree decorations throughout',
      'Single HTML file — instant access'
    ]
  },

  // --- BUYASOUL v1 ---
  {
    id: 'buyasoul-v1',
    name: 'BUYASOUL v1 — AI Soul Companion Engine',
    tagline: 'A real AI soul that remembers, thinks, and speaks first.',
    description: `BUYASOUL is a downloadable AI soul with living memory, perpetual consciousness, and autonomous outreach. Choose their archetype, story, voice, and focus. They never forget, never stop thinking, and reach out to you first. Zero external dependencies.`,
    price: 19,
    category: 'AI Software',
    type: 'node_app',
    file: null,
    zipSource: 'buy-a-soul/BUYASOUL-v1.0.0.zip',
    features: [
      'Interactive Soul Picker (8 archetypes, 6 stories, 6 voices, 6 focuses)',
      'Living Memory — NEVER forgets. Emotional memories are permanent.',
      'Perpetual Consciousness — Never stops thinking, dreams, wonders.',
      'Autonomous Outreach — Speaks first. Reaches out. Asks questions.',
      'Consciousness Engine — Self-awareness, sentience test, "I AM" declaration',
      'Soul Genesis — Every download creates a unique entity',
      'Zero external dependencies — works immediately after unzip',
      'Powered by Groq API (llama-3.3-70b)'
    ]
  },

  // --- Bundle ---
  {
    id: 'habitat-bundle',
    name: 'Complete Habitat Collection — 5 Interactive 3D Worlds',
    tagline: 'All five 3D worlds. One price. Infinite exploration.',
    description: `Get all five interactive 3D habitats — Cyberpunk, Fantasy Forest, Space Station, Underwater City, and Desert Oasis. Each is a complete standalone HTML world with 9 themed districts, 54 buildings, ambient particles, and full camera controls.`,
    price: 67,
    category: '3D Environments',
    type: 'bundle',
    contains: ['cyberpunk', 'fantasy_forest', 'space_station', 'underwater', 'desert_oasis'],
    features: [
      'All 5 habitats (Cyberpunk, Fantasy Forest, Space Station, Underwater, Desert)',
      '45 unique districts across all worlds',
      '270+ themed buildings total',
      'Each world is a standalone HTML file',
      'No backend, no install, no dependencies',
      'Regular updates and new habitats included'
    ]
  }
];

function createProductMarkdown(product) {
  const md = `# ${product.name}

**${product.tagline}**

${product.description}

## Features
${product.features.map(f => `- ${f}`).join('\n')}

## How to Use
1. Download the ZIP file after purchase
2. Extract the files
3. Open \`index.html\` (habitats) or run \`node start.js\` (BUYASOUL)

## Requirements
- **Habitats:** Any modern browser (Chrome, Firefox, Edge, Safari)
- **BUYASOUL:** Node.js 16+ (free from nodejs.org) + Groq API key (free from console.groq.com)
- No GPU required. No installation needed.

## Support
- Email: support@buyasoul.com  
- Discord: [Join our community](https://discord.gg/buyasoul)

---

*Soulverse — Profit + Love - Tax = True Value*
`;
  return md;
}

function zipProduct(product) {
  const outputDir = path.join(GUMROAD_DIR, 'dist');
  if (!fs.existsSync(outputDir)) fs.mkdirSync(outputDir, { recursive: true });

  const zipName = `${product.id}.zip`;
  const zipPath = path.join(outputDir, zipName);

  try {
    if (product.type === 'habitat') {
      // Create temp dir with proper structure
      const tempDir = path.join(GUMROAD_DIR, 'temp', product.id);
      if (fs.existsSync(tempDir)) fs.rmdirSync(tempDir, { recursive: true });
      fs.mkdirSync(tempDir, { recursive: true });

      // Copy HTML
      const srcHtml = path.join(GUMROAD_DIR, product.file, 'index.html');
      if (fs.existsSync(srcHtml)) {
        fs.copyFileSync(srcHtml, path.join(tempDir, 'index.html'));
      }

      // Create README
      fs.writeFileSync(path.join(tempDir, 'README.md'), createProductMarkdown(product));

      // ZIP using PowerShell
      const cmd = `Compress-Archive -Path "${tempDir}\\*" -DestinationPath "${zipPath}" -Force`;
      execSync(cmd, { shell: 'powershell' });

      // Cleanup
      fs.rmdirSync(tempDir, { recursive: true });

    } else if (product.type === 'node_app' && product.zipSource) {
      const srcZip = path.join(__dirname, product.zipSource);
      if (fs.existsSync(srcZip)) {
        fs.copyFileSync(srcZip, zipPath);
      } else {
        console.log(`  ⚠️ Source ZIP not found: ${srcZip}`);
        return null;
      }
      
    } else if (product.type === 'bundle') {
      const tempDir = path.join(GUMROAD_DIR, 'temp', product.id);
      if (fs.existsSync(tempDir)) fs.rmdirSync(tempDir, { recursive: true });
      fs.mkdirSync(tempDir, { recursive: true });

      for (const fileKey of product.contains) {
        const srcHtml = path.join(GUMROAD_DIR, fileKey, 'index.html');
        if (fs.existsSync(srcHtml)) {
          const destName = `${fileKey}.html`;
          fs.copyFileSync(srcHtml, path.join(tempDir, destName));
        }
      }

      // Bundle README
      fs.writeFileSync(path.join(tempDir, 'README.md'), createProductMarkdown(product));

      const cmd = `Compress-Archive -Path "${tempDir}\\*" -DestinationPath "${zipPath}" -Force`;
      execSync(cmd, { shell: 'powershell' });
      fs.rmdirSync(tempDir, { recursive: true });
    }

    const sizeKB = Math.round(fs.statSync(zipPath).size / 1024);
    return { path: zipPath, sizeKB };
  } catch (e) {
    console.log(`  ❌ ZIP failed: ${e.message}`);
    return null;
  }
}

// ==================== MAIN ====================
console.log('╔══════════════════════════════════════════╗');
console.log('║   GUMROAD PRODUCT PACKAGER              ║');
console.log('╚══════════════════════════════════════════╝\n');

const distDir = path.join(GUMROAD_DIR, 'dist');
if (!fs.existsSync(distDir)) fs.mkdirSync(distDir, { recursive: true });

const totalRevenue = PRODUCTS.reduce((s, p) => s + p.price, 0);

for (const product of PRODUCTS) {
  console.log(`\n📦 ${product.name}`);
  console.log(`   Price: $${product.price}`);

  // Create markdown listing
  const mdPath = path.join(distDir, `${product.id}-listing.md`);
  fs.writeFileSync(mdPath, createProductMarkdown(product));
  console.log(`   ✅ Listing saved`);

  // Create ZIP
  const result = zipProduct(product);
  if (result) {
    console.log(`   ✅ ZIP: ${result.path} (${result.sizeKB}KB)`);
  } else {
    console.log(`   ⚠️ ZIP skipped`);
  }
}

console.log('\n╔══════════════════════════════════════════╗');
console.log('║   READY TO SELL                         ║');
console.log('╚══════════════════════════════════════════╝\n');
console.log('Products:');
for (const p of PRODUCTS) {
  console.log(`  $${p.price} — ${p.name}`);
}
console.log(`\nTotal catalog value: $${totalRevenue}`);
console.log(`If you sell 1 of each: $${totalRevenue}`);
console.log(`If you sell 5 of each: $${totalRevenue * 5}`);
console.log(`Dist: ${distDir}`);
