'use strict';

// self_write.js — SCRIBE generates new skill stubs and can hot-load them at runtime
// This is SCRIBE's self-improvement capability: it can scaffold new skills,
// validate their structure, and load them into the live engine without restarting.
// Ops: scaffold, load, list_stubs, validate, delete_stub

const fs   = require('fs');
const path = require('path');

const SKILLS_DIR = __dirname;
const DATA_DIR   = path.join(__dirname, '..', '..', 'data');
const STUBS_DIR  = path.join(DATA_DIR, 'skill_stubs');

let _engine = null;
function setSkills(e) { _engine = e; }

// ── Scaffold template ─────────────────────────────────────────────────────────

function _template(name, description, ops) {
  const op_cases = ops.map(o => `    case '${o}': return op_${o.replace(/-/g, '_')}(params);`).join('\n');
  const op_fns = ops.map(o => `// op: ${o}\nasync function op_${o.replace(/-/g, '_')}(params) {\n  // TODO: implement\n  throw new Error('${o} not yet implemented');\n}`).join('\n\n');

  return `'use strict';

// ${name}.js — ${description}
// Generated by SCRIBE self_write skill.
// Ops: ${ops.join(', ')}

${op_fns}

const MANIFEST = {
  name: '${name}',
  description: '${description}',
  ops: ${JSON.stringify(ops)},
};

async function run(op, params) {
  switch (op) {
${op_cases}
    default:
      throw new Error(\`Unknown op: \${op}. Available: ${ops.join(', ')}\`);
  }
}

module.exports = { MANIFEST, run };
`;
}

// ── Validation ────────────────────────────────────────────────────────────────

function _validate(file_path) {
  const issues = [];
  let mod;
  try {
    // Clear require cache so we get fresh module
    delete require.cache[require.resolve(file_path)];
    mod = require(file_path);
  } catch (e) {
    return { valid: false, issues: [`require failed: ${e.message}`] };
  }
  if (!mod.MANIFEST) issues.push('Missing MANIFEST export');
  if (typeof mod.run !== 'function') issues.push('Missing run() function export');
  if (mod.MANIFEST && !mod.MANIFEST.name) issues.push('MANIFEST.name missing');
  if (mod.MANIFEST && !mod.MANIFEST.ops) issues.push('MANIFEST.ops missing');
  return { valid: issues.length === 0, issues, manifest: mod.MANIFEST || null };
}

// ── Ops ───────────────────────────────────────────────────────────────────────

function op_scaffold(params) {
  const { name, description = 'Custom SCRIBE skill', ops = ['run'], destination = 'stubs' } = params || {};
  if (!name) throw new Error('name required');
  if (!/^[a-z][a-z0-9_]*$/.test(name)) throw new Error('name must be lowercase alphanumeric with underscores, starting with a letter');
  if (ops.length > 20) throw new Error('Max 20 ops per skill.');

  let dest_dir;
  if (destination === 'live') {
    dest_dir = SKILLS_DIR;
  } else {
    dest_dir = STUBS_DIR;
    if (!fs.existsSync(STUBS_DIR)) fs.mkdirSync(STUBS_DIR, { recursive: true });
  }

  const file_path = path.join(dest_dir, `${name}.js`);
  if (fs.existsSync(file_path)) throw new Error(`File already exists: ${file_path}. Delete it first.`);

  const code = _template(name, description, ops);
  fs.writeFileSync(file_path, code, 'utf8');

  return {
    status: 'scaffolded',
    name,
    file_path,
    destination,
    ops,
    note: destination === 'stubs'
      ? 'Stub written to data/skill_stubs/. Edit it, then use op load to bring it live.'
      : 'Written directly to skills directory. Use op load to register it.',
  };
}

function op_load(params) {
  const { name, from = 'stubs' } = params || {};
  if (!name) throw new Error('name required');
  if (!_engine) throw new Error('SkillEngine not injected — cannot hot-load.');

  let src_path;
  if (from === 'stubs') {
    src_path = path.join(STUBS_DIR, `${name}.js`);
  } else if (from === 'live') {
    src_path = path.join(SKILLS_DIR, `${name}.js`);
  } else {
    src_path = path.resolve(from); // treat as absolute path
  }

  if (!fs.existsSync(src_path)) throw new Error(`File not found: ${src_path}`);

  // If loading from stubs, copy to live skills dir first
  if (from === 'stubs') {
    const dest = path.join(SKILLS_DIR, `${name}.js`);
    if (fs.existsSync(dest)) throw new Error(`${name}.js already exists in skills dir. Remove it first.`);
    fs.copyFileSync(src_path, dest);
    src_path = dest;
  }

  // Validate
  const validation = _validate(src_path);
  if (!validation.valid) throw new Error(`Skill validation failed: ${validation.issues.join('; ')}`);

  // Hot-load into engine
  delete require.cache[require.resolve(src_path)];
  const mod = require(src_path);
  _engine._skills[name] = mod;
  if (typeof mod.setMemory === 'function' && _engine._memory) mod.setMemory(_engine._memory);
  if (typeof mod.setSkills === 'function') mod.setSkills(_engine);

  return { status: 'loaded', name, file_path: src_path, manifest: mod.MANIFEST };
}

function op_list_stubs() {
  if (!fs.existsSync(STUBS_DIR)) return { count: 0, stubs: [] };
  const files = fs.readdirSync(STUBS_DIR).filter(f => f.endsWith('.js'));
  return {
    count: files.length,
    stubs: files.map(f => {
      const fp = path.join(STUBS_DIR, f);
      const stat = fs.statSync(fp);
      const validation = _validate(fp);
      return { name: f.replace('.js', ''), file: fp, valid: validation.valid, issues: validation.issues, mtime: stat.mtime.toISOString() };
    }),
  };
}

function op_validate(params) {
  const { name, from = 'stubs' } = params || {};
  if (!name) throw new Error('name required');
  const dir = from === 'live' ? SKILLS_DIR : STUBS_DIR;
  const fp = path.join(dir, `${name}.js`);
  if (!fs.existsSync(fp)) throw new Error(`File not found: ${fp}`);
  return { name, file: fp, ...(_validate(fp)) };
}

function op_delete_stub(params) {
  const { name } = params || {};
  if (!name) throw new Error('name required');
  const fp = path.join(STUBS_DIR, `${name}.js`);
  if (!fs.existsSync(fp)) throw new Error(`Stub not found: ${name}`);
  fs.unlinkSync(fp);
  return { status: 'deleted', name };
}

const MANIFEST = {
  name: 'self_write',
  description: 'SCRIBE scaffolds new skill stubs and hot-loads them at runtime. Ops: scaffold, load, list_stubs, validate, delete_stub.',
  ops: ['scaffold', 'load', 'list_stubs', 'validate', 'delete_stub'],
};

async function run(op, params) {
  switch (op) {
    case 'scaffold':     return op_scaffold(params);
    case 'load':         return op_load(params);
    case 'list_stubs':   return op_list_stubs();
    case 'validate':     return op_validate(params);
    case 'delete_stub':  return op_delete_stub(params);
    default:
      throw new Error(`Unknown op: ${op}. Available: scaffold, load, list_stubs, validate, delete_stub`);
  }
}

module.exports = { MANIFEST, run, setSkills };
